// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testMsg.proto

#ifndef PROTOBUF_testMsg_2eproto__INCLUDED
#define PROTOBUF_testMsg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace test_package {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_testMsg_2eproto();
void protobuf_AssignDesc_testMsg_2eproto();
void protobuf_ShutdownFile_testMsg_2eproto();

class testMsg;

// ===================================================================

class testMsg : public ::google::protobuf::Message {
 public:
  testMsg();
  virtual ~testMsg();

  testMsg(const testMsg& from);

  inline testMsg& operator=(const testMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const testMsg& default_instance();

  void Swap(testMsg* other);

  // implements Message ----------------------------------------------

  testMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const testMsg& from);
  void MergeFrom(const testMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 sendtime = 1;
  inline bool has_sendtime() const;
  inline void clear_sendtime();
  static const int kSendtimeFieldNumber = 1;
  inline ::google::protobuf::int32 sendtime() const;
  inline void set_sendtime(::google::protobuf::int32 value);

  // required string msg = 2;
  inline bool has_msg() const;
  inline void clear_msg();
  static const int kMsgFieldNumber = 2;
  inline const ::std::string& msg() const;
  inline void set_msg(const ::std::string& value);
  inline void set_msg(const char* value);
  inline void set_msg(const char* value, size_t size);
  inline ::std::string* mutable_msg();
  inline ::std::string* release_msg();
  inline void set_allocated_msg(::std::string* msg);

  // @@protoc_insertion_point(class_scope:test_package.testMsg)
 private:
  inline void set_has_sendtime();
  inline void clear_has_sendtime();
  inline void set_has_msg();
  inline void clear_has_msg();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* msg_;
  ::google::protobuf::int32 sendtime_;
  friend void  protobuf_AddDesc_testMsg_2eproto();
  friend void protobuf_AssignDesc_testMsg_2eproto();
  friend void protobuf_ShutdownFile_testMsg_2eproto();

  void InitAsDefaultInstance();
  static testMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// testMsg

// required int32 sendtime = 1;
inline bool testMsg::has_sendtime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void testMsg::set_has_sendtime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void testMsg::clear_has_sendtime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void testMsg::clear_sendtime() {
  sendtime_ = 0;
  clear_has_sendtime();
}
inline ::google::protobuf::int32 testMsg::sendtime() const {
  // @@protoc_insertion_point(field_get:test_package.testMsg.sendtime)
  return sendtime_;
}
inline void testMsg::set_sendtime(::google::protobuf::int32 value) {
  set_has_sendtime();
  sendtime_ = value;
  // @@protoc_insertion_point(field_set:test_package.testMsg.sendtime)
}

// required string msg = 2;
inline bool testMsg::has_msg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void testMsg::set_has_msg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void testMsg::clear_has_msg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void testMsg::clear_msg() {
  if (msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_->clear();
  }
  clear_has_msg();
}
inline const ::std::string& testMsg::msg() const {
  // @@protoc_insertion_point(field_get:test_package.testMsg.msg)
  return *msg_;
}
inline void testMsg::set_msg(const ::std::string& value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
  // @@protoc_insertion_point(field_set:test_package.testMsg.msg)
}
inline void testMsg::set_msg(const char* value) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  msg_->assign(value);
  // @@protoc_insertion_point(field_set_char:test_package.testMsg.msg)
}
inline void testMsg::set_msg(const char* value, size_t size) {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  msg_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:test_package.testMsg.msg)
}
inline ::std::string* testMsg::mutable_msg() {
  set_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    msg_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:test_package.testMsg.msg)
  return msg_;
}
inline ::std::string* testMsg::release_msg() {
  clear_has_msg();
  if (msg_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = msg_;
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void testMsg::set_allocated_msg(::std::string* msg) {
  if (msg_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete msg_;
  }
  if (msg) {
    set_has_msg();
    msg_ = msg;
  } else {
    clear_has_msg();
    msg_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:test_package.testMsg.msg)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace test_package

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_testMsg_2eproto__INCLUDED
